apiVersion: apps/v1
kind: Deployment
metadata:
  name: tschatserver
spec:
  selector:
    matchLabels:
      app: tschatserver
  template:
    metadata:
      labels:
        app: tschatserver
    spec:
      imagePullSecrets:
        - name: localdockersecrets
      containers:
      - name: tschatserver
        image: registry.fprog.club/tschatserver:{{ tag }}
        resources:
          limits:
            memory: "64Mi"
            cpu: "50m"
        ports:
        - containerPort: 8022
---
apiVersion: v1
kind: Service
metadata:
  name: tschatserver
spec:
  selector:
    app: tschatserver
  ports:
  - port: 8022
    targetPort: 8022
